baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Mon Portofolio Hugo'
theme = 'iutdelens'

[[menu.main]]
name = "À propos"
url = "/a-propos-de"
[[menu.main]]
name = "Blog"
url = "/projet/2022"

[[menu.social]]
name = "GitHub"
url = "https://github.com/JonIsamb"
pre = "<i class='fab fa-github'></i>"
[[menu.social]]
name = "Twitter"
url = "https://twitter.com/entomdaora"
pre = "<i class='fab fa-twitter'></i>"


[[menu.footer]]
name = "À propos"
url = "/a-propos-de"

[params]
    author = "Moi"
    authorImage = "/images/avatar.jpg"
